// <auto-generated />
namespace IT_BookTrade.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class add_Wishlist : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_Wishlist));
        
        string IMigrationMetadata.Id
        {
            get { return "201808011832415_add_Wishlist"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
